project:
  type: website
  output-dir: _site
  resources:
    - "google*.html"
website:
  title: "Idan Franco"
  description: "Idan Franco, PhD Student in Political Science at UIUC"
  site-url: "https://www.idanfranco.com"
  favicon: img/favicon.png
  open-graph: true
  twitter-card: true
  navbar:
    pinned: true
    background: light
    foreground: black
format:
  html:
    theme: cosmo
    css: styles.css
    toc: false
    page-layout: article
    fontsize: 1rem
    linestretch: 1.6
    include-in-header: _head.html
    include-before-body: _hero-left.html
    grid:
      body-width: 1240px
      sidebar-width: 0px
      margin-width: 0px
